config/routes.rb
Rails.application.routes.draw do

  resources :payments, only: [:index] do
    get :callback, on: :collection
    get :incoming, on: :collection
    get :outgoing, on: :collection
  end

  resources :tags, only: :index

  ActiveAdmin.routes(self)

  get 'sitemap.xml', :to => 'sitemaps#index', :defaults => {:format => 'xml'}
  get 'discourse/sso', to: 'discourse_sso#sso'

  resources :ideas do
    patch :repost, on: :member
    resources :payments, only: :create
    resources :flags, only: :create
    resources :implementations, only: [:index, :create, :new, :show]
    resources :comments, only: :create
    resources :backer_votes, only: [:new, :create]
  end

  resources :comments, only: [] do
    resources :flags, only: :create
  end

  resources :votes, only: [] do
    get :start, on: :collection
    post :finish, on: :collection
  end

  resources :users, only: [] do
    resources :ideas, only: [:index]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get :terms, to: 'main#terms'
  get :search, to: 'main#search'
  get :about, to: 'main#about'
  get :contest, to: 'main#contest'
  get :privacy_policy, to: 'main#privacy_policy'
  root to: 'main#index'
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessor :tos_accepted
  attr_accessor :video_url

  include AlgoliaSearch

  mount_uploader :picture, PictureUploader

  algoliasearch per_environment: true, disable_indexing: Rails.env.test? do
    attribute :title, :tag_list, :summary, :description
  end

  acts_as_commentable
  acts_as_taggable

  belongs_to :user
  belongs_to :implementation
  has_many :incoming_payments, as: :recipient, class_name: 'Payment'
  has_many :outgoing_payments, as: :sender, class_name: 'Payment'

  has_many :positive_votes, class_name: 'Vote',
           inverse_of: :positive_idea, foreign_key: 'positive_idea_id'

  has_many :negative_votes, class_name: 'Vote',
           inverse_of: :negative_idea, foreign_key: 'negative_idea_id'

  has_many :flags, as: :flaggable
  has_many :implementations

  has_many :backer_votes

  MAX_SUMMARY_LENGTH = 200

  SAFE_ORDERS = {
      newest: 'ideas.posted_at DESC',
      oldest: 'ideas.posted_at ASC',
      backers: 'ideas.backers_count DESC',
      balance: 'ideas.amount_raised DESC',
      rating: '(positive_votes_count::float / (positive_votes_count + negative_votes_count + 1)) DESC'
  }

  validates :title, presence: true, uniqueness: true, length: { maximum: 60 }
  validates :summary, presence: true, length: { maximum: MAX_SUMMARY_LENGTH }
  validates :user, presence: true
  validates :tos_accepted, acceptance: { accept: '1' }
  validates :balance, numericality: { greater_than_or_equal_to: 0 }
  validates :video_url, youtube_url: true

  default_scope { order(posted_at: :desc) }

  scope :current, -> { where('posted_at BETWEEN ? AND ?', Date.today.beginning_of_month, Date.today.next_month.beginning_of_month) }
  scope :previous, -> { where('posted_at BETWEEN ? AND ?', Date.today.prev_month.beginning_of_month, Date.today.beginning_of_month)  }
  scope :safe_order, -> (order_str){ unscope(:order).order(SAFE_ORDERS.fetch(order_str){ SAFE_ORDERS[:rating] }) }
  scope :visible, -> { where('ideas.flags_count < ? OR approved = ?', 5, true) }
  scope :pending_for_backer_voting, -> { where(backer_voting_result: 'extend').where('ideas.posted_at < ?', Date.today.beginning_of_month) }
  scope :fee_processing_eligible, -> { where('posted_at < ? AND balance > 0', Date.today.beginning_of_month - 1.month) }

  before_update :update_amount_raised, if: :balance_changed?
  before_save :set_video_info
  before_create :reset_posted_at

  def rating
    (positive_votes_count + 1).to_f / ( positive_votes_count + negative_votes_count + 2 )
  end

  def formatted_rating
    sprintf('%.2f', rating * 10)
  end

  def in_voting_phase?
    posted_at > Date.today.beginning_of_month && posted_at < Date.today.end_of_month + 1.day
  end

  def in_proposals_phase?
    return false if in_voting_phase?
    Date.today.day.between?(1, 21) && backer_voting_result == 'extend'
  end

  def in_backer_voting_phase?
    return false if in_voting_phase?
    backer_voting_result == 'extend'
  end

  def increment_backers_count!(sender)
    increment!(:backers_count) if incoming_payments.successful.where(sender: sender).count == 1
  end

  def calculate_backers_count
    update_column :backers_count, unique_backers_count
  end

  def unique_backers_count
    incoming_payments.successful.select(:sender_id).distinct.count
  end

  def top_backer_vote
    backer_votes_counts = backer_votes.select('MAX(backer_votes.kind) AS kind, max(backer_votes.implementation_id) as implementation_id, COUNT(backer_votes.id) AS count').group('backer_votes.kind')
    maximums = backer_votes_counts.max_by(2){|bv| bv.count}
    case
      when maximums.length == 0                   then return false
      when maximums.length == 1                   then return maximums[0]
      when maximums[0].count == maximums[1].count then return false
      else                                             return maximums[0]
    end
  end

  def set_voting_result
    backer_vote = top_backer_vote
    return unless backer_vote
    attrs = { backer_voting_result: backer_vote.kind }
    attrs.merge!(implementation_id: backer_vote.implementation_id) if backer_vote.implementation_id
    update(attrs)
  end

  def update_amount_raised
    return if balance <= balance_was
    self.amount_raised = balance
  end

  def process_payments
    process_ideadash_fee
    process_author_fee
  end

  def self.process_eligible_payments
    fee_processing_eligible.map(&:process_payments)
  end

  def self.count_backer_voting_results
    pending_for_backer_voting.find_each do |idea|
      idea.set_voting_result
    end
  end

  def video_url
    return @video_url if @video_url.present?
    YoutubeUrl.convert_back video_id, video_time
  end

  def set_video_info
    youtube_url = YoutubeUrl.new video_url
    self.video_id, self.video_time = youtube_url.process
  end

  def reset_posted_at
    self.posted_at = Time.now
  end

  private
  def process_ideadash_fee
    return if ideadash_fee_processed
    ideadash_fee = amount_raised * 0.05
    outgoing_payments.create!(amount: ideadash_fee, recipient: User.find(ENV['IDEADASH_ADMIN_ID']))
    update_column :ideadash_fee_processed, true
  end

  def process_author_fee
    return if author_fee_processed
    author_fee = amount_raised * 0.1
    outgoing_payments.create!(amount: author_fee, recipient: user)
    update_column :author_fee_processed, true
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  load_and_authorize_resource :user, only: [:index]
  load_and_authorize_resource :idea, through: :user, shallow: true

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = @ideas.paginate(:page => params[:page]).visible
    @ideas = @ideas.includes(:user) unless @user
    @ideas = @ideas.send(params.fetch(:filter){ :current })
    @ideas = @ideas.safe_order(params.fetch(:order){ :rating }.to_sym)
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    flash.now[:warning] = 'Funding was canceled' if params[:status] == 'canceled'
    @new_comment = Comment.build_from(@idea, current_user.try(:id), "")
  end

  # GET /ideas/new
  def new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, success: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def repost
    @idea.reset_posted_at and @idea.save
    redirect_to @idea, success: 'Idea was successfully reposted.'
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:title, :summary, :description, :tos_accepted, :video_url, :tag_list, :picture, :picture_cache)
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
  ORDER_MAPPING = {
      rating: 'Highest rated',
      # backers: 'Most backers',
      # balance: 'Total funds raised',
      newest: 'Newest first',
      oldest: 'Oldest first'
  }
  FILTER_MAPPING = {
      current: 'Current month',
      previous: 'Previous month',
      all: 'All'
  }

  def order_dropdown
    dropdown ORDER_MAPPING.fetch(params[:order].try(:to_sym)){ 'Highest rated' } do
      ORDER_MAPPING.map do |k, v|
        link_to(v, current_ideas_path(filter: params[:filter], order: k))
      end.join('').html_safe
    end
  end

  def filter_dropdown
    dropdown FILTER_MAPPING.fetch(params[:filter].try(:to_sym)){ 'Current month' } do
      FILTER_MAPPING.map do |k, v|
        link_to(v, current_ideas_path(filter: k, order: params[:order]))
      end.join('').html_safe
    end
  end

  def decimal_number n
    sprintf('%.2f', n)
  end

  private
  def current_ideas_path(*args)
    @user ? user_ideas_path(@user, *args) : ideas_path(*args)
  end
end

app/views/ideas/_form.html.slim
= simple_form_for(@idea, html: { class: 'with_short_fields' }) do |f|
  = f.error_notification
  .form-inputs
    = f.input :title, hint: '{{ titleLength }}', input_html: { 'v-model' => 'title' }, hint_html: { 'v-if' => 'showTitleHint' }
    = f.input :summary, as: :text, hint: '{{ summaryLength }}', input_html: { 'v-model' => 'summary' }, hint_html: { 'v-if' => 'showSummaryHint' }
    = f.input :tag_list, input_html: { class: 'tag_list', value: @idea.tag_list.join(',') }
    = f.input :user_name, label: 'Author Name', required: true do
      = text_field :idea, :user_name, value: current_user.name, disabled: true, class: 'form-control'
    = f.input :description
    h4 To draw more attention to your idea, you can either:
    = f.hidden_field :picture_cache
    = f.input :picture, as: :file, label: 'Upload an Image'
    = f.input :video_url, label: 'Or Provide YouTube video URL', hint: "You can paste a Youtube video URL here. Also, you can use Youtube's \"Share\" function to link to a specific time mark"
    = f.input :tos_accepted, as: :boolean, label: 'I accept Terms of Service and understand that by posting my idea anyone will be able to use it or implement it.' if @idea.new_record?
  .form-actions
    .btn-group
      = f.button :submit, class: 'btn btn-primary'
      = link_to 'Back', :back, class: 'btn btn-default'

app/views/ideas/_idea.slim
= content_tag_for :tr, idea do
  td
    h4
      = link_to idea.title.gsub(/\W$/, ''), idea
      span.idea-author
        '  by
        = idea.user.name
        '
        i.fa.fa-dollar[title="Total Funds"]
        '  #{ decimal_number idea.amount_raised }
        i.fa.fa-user[title="Total Backers"]
        '  #{ idea.backers_count }
    = idea.summary
  - if @user
    td= link_to 'Repost', repost_idea_path(idea), method: :patch, class: 'btn btn-success btn-xs' if can? :repost, idea
    td= link_to 'Edit', edit_idea_path(idea), class: 'btn btn-warning btn-xs' if can? :edit, idea
    td= link_to 'Delete', idea_path(idea), method: :delete,
            data: { confirm: 'Are you sure? This action is irreversible.' },
            class: 'btn btn-danger btn-xs' if can? :destroy, idea

app/views/ideas/edit.html.slim
- provide :title, 'Edit idea'
.col-xs-12.col-md-6.col-md-offset-3
  h1 Editing Idea
  - if @idea.negative_votes_count > 3
    p.text-muted
      ' We do not encourage making major updates to idea even if it is low-rated.
      ' If you believe your idea was misunderstood, or its explanation needs to be revised, feel free to edit it.
      ' In all other cases we recommend you to re-consider it, prepare new summary and title, and post it again, to get more attention.
      strong But please, do not post the same idea more than twice.
  = render 'form'

app/views/ideas/index.html.slim
- provide :title, 'Ideas'
- provide :description, 'See all ideas posted by other idea authors, and submit your own!'
.col-xs-12.col-md-offset-2.col-md-8
  h3.hidden-xs
    ' Showing
    = filter_dropdown
    '  ideas sorted by
    = order_dropdown
  h5.visible-xs
    .pull-left= filter_dropdown
    .pull-right= order_dropdown
  table.table#ideas
    tbody
      = render @ideas
      - if @ideas.empty?
        tr
          - if @user
            td[colspan="5"]
              h5
                ' During this month, you did not post your ideas yet.
                = link_to 'Post one!', new_idea_path
          - else
            td[colspan="3"]
              h5
                ' During this month, nobody posted his idea yet.
                = link_to 'Be the first!', new_idea_path
  = will_paginate @ideas, renderer: BootstrapPagination::Rails

app/views/ideas/new.html.slim
- provide :title, 'New idea'
.col-xs-12.col-md-6.col-md-offset-3
  h1 Post an idea
  = render 'form'

app/views/ideas/show.html.slim
- provide :title, @idea.title
- provide :description, @idea.summary
- if @idea.video_id
  - provide :image, "http://img.youtube.com/vi/#{ @idea.video_id }/mqdefault.jpg"

.col-xs-12.col-md-8.col-md-offset-2
  .jumbotron.text-center
    - if user_signed_in? && current_user.can_flag?(@idea)
      .dropdown.flag( class="flag-Idea-#{@idea.id}" )
        a.dropdown-toggle[href='javascript:void(0);' data-toggle='dropdown']
          i.fa.fa-flag-o
        .dropdown-menu.flag-form
          = simple_form_for [@idea, Flag.new], remote: true do |f|
            = f.input :kind, as: :radio_buttons, collection: Flag::KINDS.map{|k,v| [v,k]}, label: false
            = f.input :description, placeholder: 'Comment, link...', label: false
            = f.submit 'Report', class: 'btn btn-small btn-info'
    - if @idea.video_id.present?
      = embed_video @idea
      h3= @idea.title
      p
        ' by
        = @idea.user.name
      p= @idea.summary
    - elsif @idea.picture.present?
      = image_tag @idea.picture_url, alt: @idea.title, class: 'img-responsive'
      h3= @idea.title
      p
        ' by
        = @idea.user.name
      p= @idea.summary
    - else
      h1= @idea.title
      p
        ' by
        = @idea.user.name
      p= @idea.summary
    - if can?(:manage, Payment) && @idea.in_voting_phase? && false
      .row
        .col-xs-12.col-md-6.col-md-offset-3
          = simple_form_for [@idea, Payment.new], html: { data: { balance: sprintf('%.2f', current_user.balance) } } do |f|
            .input-group
              .input-group-addon
                i.fa.fa-dollar
              = f.number_field :amount, class: 'form-control', min: 1, value: '0.00', 'v-model' => 'fundedAmount'
              .input-group-btn= f.submit 'Donate', class: 'btn btn-primary', 'v-on:click.prevent' => 'confirmAction', ':disabled' => 'isInvalidAmount'
    .votes
      span.votes-up
        i.fa.fa-line-chart(title='Rating out of 10.0')
        = @idea.formatted_rating
      span.funded.hidden
        i.fa.fa-dollar(title='Amount Raised')
        = decimal_number @idea.amount_raised
      span.backers
        i.fa.fa-user(title='Total Backers')
        = @idea.backers_count
      span.share.hidden-xs
        i.fa.fa-share-alt(title='Share')
        .share-popup
          a.share-link.twitter target="_blank" href="https://twitter.com/intent/tweet?text=#{ url_encode("Check this out: #{ @idea.title }") }&url=#{ idea_url(@idea) }"
            i.fa.fa-twitter
          a.share-link.facebook target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=#{ idea_url(@idea) }"
            i.fa.fa-facebook
          a.share-link.email href="mailto:?subject=#{ url_encode("Check this out: #{ @idea.title }") }&body=#{ idea_url(@idea) }"
            i.fa.fa-envelope-o
      .share.share-block.visible-xs
        a.share-link.twitter target="_blank" href="https://twitter.com/intent/tweet?text=#{ url_encode("Check this out: #{ @idea.title }") }&url=#{ idea_url(@idea) }"
          i.fa.fa-twitter
        a.share-link.facebook target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=#{ idea_url(@idea) }"
          i.fa.fa-facebook
        a.share-link.email href="mailto:?subject=#{ url_encode("Check this out: #{ @idea.title }") }&body=#{ idea_url(@idea) }"
          i.fa.fa-envelope-o

    .votes.btn-group
      - if user_signed_in? && can?(:create, current_user.implementations.build(idea: @idea))
        = link_to 'Propose an implementation', new_idea_implementation_path(@idea), class: 'btn btn-success'
      - if user_signed_in? && can?(:create, BackerVote.new(user: current_user, idea: @idea))
        = link_to 'Vote for implementation', new_idea_backer_vote_path(@idea), class: 'btn btn-info'
  p= simple_format @idea.description
  - if @idea.backer_voting_result == 'refund'
    p.lead Idea backers have voted to refund money back to their accounts; no proposal has been selected.
  - if @idea.backer_voting_result == 'vote' && @idea.implementation
    p.lead
      ' This idea will be implemented according to
      = link_to @idea.implementation.title, idea_implementation_path(@idea, @idea.implementation)
      '  by
      = @idea.implementation.user.name
  - else
    - if @idea.implementations.any?
      h3 Implementation proposals submitted:
      table.table#implementations
        thead
          tr
            th Title
            th Summary
            th.hidden-xs User
        tbody
          = render @idea.implementations.includes(:user)
  = render partial: 'comments/template', locals: { commentable: @idea, new_comment: @comment }