config/routes.rb
Rails.application.routes.draw do

  resources :payments, only: [:index] do
    get :callback, on: :collection
    get :incoming, on: :collection
    get :outgoing, on: :collection
  end

  resources :tags, only: :index

  ActiveAdmin.routes(self)

  get 'sitemap.xml', :to => 'sitemaps#index', :defaults => {:format => 'xml'}
  get 'discourse/sso', to: 'discourse_sso#sso'

  resources :ideas do
    patch :repost, on: :member
    resources :payments, only: :create
    resources :flags, only: :create
    resources :implementations, only: [:index, :create, :new, :show]
    resources :comments, only: :create
    resources :backer_votes, only: [:new, :create]
  end

  resources :comments, only: [] do
    resources :flags, only: :create
  end

  resources :votes, only: [] do
    get :start, on: :collection
    post :finish, on: :collection
  end

  resources :users, only: [] do
    resources :ideas, only: [:index]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get :terms, to: 'main#terms'
  get :search, to: 'main#search'
  get :about, to: 'main#about'
  get :contest, to: 'main#contest'
  get :privacy_policy, to: 'main#privacy_policy'
  root to: 'main#index'
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
  layout nil
  caches_action :index, expires_in: 12.hours

  def index
    headers['Content-Type'] = 'application/xml'
    respond_to do |format|
      format.xml
    end
  end
end

app/views/sitemaps/index.xml.slim
doctype xml
urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  url
    loc= root_url
    lastmod= Date.today.beginning_of_day.iso8601
    changefreq = 'always'
    priority 1
  url
    loc= about_url
    lastmod= Date.today.beginning_of_day.iso8601
    changefreq = 'weekly'
    priority 1
  url
    loc= ideas_url
    lastmod= Date.today.beginning_of_day.iso8601
    changefreq = 'always'
    priority 1
  - Idea.all.each do |idea|
    url
      loc= idea_url(idea)
      lastmod= idea.updated_at.iso8601
      - if idea.posted_at > 2.months.ago
        changefreq = 'daily'
        priority 1
      - elsif idea.posted_at > 6.months.ago
        changefreq = 'monthly'
        priority 0.5
      - else
        changefreq = 'yearly'
        priority 0.4