config/routes.rb
Rails.application.routes.draw do

  resources :payments, only: [:index] do
    get :callback, on: :collection
    get :incoming, on: :collection
    get :outgoing, on: :collection
  end

  resources :tags, only: :index

  ActiveAdmin.routes(self)

  get 'sitemap.xml', :to => 'sitemaps#index', :defaults => {:format => 'xml'}
  get 'discourse/sso', to: 'discourse_sso#sso'

  resources :ideas do
    patch :repost, on: :member
    resources :payments, only: :create
    resources :flags, only: :create
    resources :implementations, only: [:index, :create, :new, :show]
    resources :comments, only: :create
    resources :backer_votes, only: [:new, :create]
  end

  resources :comments, only: [] do
    resources :flags, only: :create
  end

  resources :votes, only: [] do
    get :start, on: :collection
    post :finish, on: :collection
  end

  resources :users, only: [] do
    resources :ideas, only: [:index]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get :terms, to: 'main#terms'
  get :search, to: 'main#search'
  get :about, to: 'main#about'
  get :contest, to: 'main#contest'
  get :privacy_policy, to: 'main#privacy_policy'
  root to: 'main#index'
end

app/views/shared/_facebook.slim
javascript:
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  document,'script','https://connect.facebook.net/en_US/fbevents.js');

  fbq('init', '503860393144339');
  fbq('track', "PageView");

- if (fbq = session.delete(:fbq))
  javascript:
    fbq('track', #{ fbq.html_safe });

noscript
  img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=503860393144339&ev=PageView&noscript=1"

app/views/shared/_footer.slim
.footer
  .container
    .row
      .col-xs-12
        = link_to 'Privacy', privacy_policy_path
        = link_to 'Terms', terms_path
        .dropup-wrapper
          = link_to 'Community', 'javascript:void(0);', 'data-toggle' => 'dropdown'
          .dropup.dropdown-menu
            = link_to 'https://www.facebook.com/ideadash', target: '_blank' do
              strong Facebook Page
              div.small Join ideaDash's official page for updates
            = link_to 'https://www.facebook.com/groups/ideaDash', target: '_blank' do
              strong Facebook Group
              div.small Join others to discuss ideas and ideaDash
        = link_to 'About', about_path

app/views/shared/_google.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m= s.getElementsByTagName(o)[0]; a.async=1; a.src=g;m.parentNode.insertBefore(a, m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-58065166-2', 'auto');
  ga('send', 'pageview');
javascript:
  var google_conversion_id = 957340062;
  var google_custom_params = window.google_tag_params;
  var google_remarketing_only = true;
script src="//www.googleadservices.com/pagead/conversion.js" type="text/javascript"
noscript
  div style="display:inline;"
    img alt="" height="1" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/957340062/?value=0&amp;guid=ON&amp;script=0" style="border-style:none;" width="1" /

app/views/shared/_header.html.slim
= navbar do
  = vertical do
    = link_to root_path do
      |  Idea
      em
        | Dash
  = horizontal do
    = nav class: 'navbar-right' do
      - if user_signed_in?
        = link_to "Welcome, #{current_user.name}!", 'javascript:void(0)'
        = link_to 'Logout', destroy_user_session_path, method: :delete
      - else
        = link_to 'Login with Facebook', user_facebook_omniauth_authorize_path

app/views/shared/_navbar.html.slim
= navbar do
  = vertical do
    = link_to root_path do
      |  idea
      em
        | dash
      span.text-beta
        ' beta
  = horizontal do
    = nav class: 'navbar-right' do
      = link_to 'How it works', about_path
      = link_to 'Explore Ideas', ideas_path
      - if can? :create, Idea
        = link_to 'Post an Idea', new_idea_path
      - if can? :start, Vote
        = link_to 'Rate Ideas', start_votes_path
      - if user_signed_in?
        = link_to 'My Ideas', user_ideas_path(current_user), class: 'visible-xs-block'
        = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'visible-xs-block'
        li.hidden-xs: p.navbar-text Welcome, #{current_user.name}!
      - else
      = link_to search_path do
        i.fa.fa-search
      - if user_signed_in?
        li.dropdown.hidden-xs
          a href="#" class="dropdown-toggle" data-toggle="dropdown"
            i.fa.fa-cogs
          ul.dropdown-menu
            li= link_to 'My Ideas', user_ideas_path(current_user)
            - if false
              li= link_to "My balance: $#{ sprintf('%.2f', current_user.balance) }", payments_path
            li= link_to 'Logout', destroy_user_session_path, method: :delete
      - else
        li.dropdown.hidden-xs
          a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Login"
            i.fa.fa-sign-in
          ul.dropdown-menu.login
            li= link_to user_google_oauth2_omniauth_authorize_path do
              i.fa.fa-google[title="Google"]
            li= link_to user_facebook_omniauth_authorize_path do
              i.fa.fa-facebook[title="Facebook"]