config/routes.rb
Rails.application.routes.draw do

  resources :payments, only: [:index] do
    get :callback, on: :collection
    get :incoming, on: :collection
    get :outgoing, on: :collection
  end

  resources :tags, only: :index

  ActiveAdmin.routes(self)

  get 'sitemap.xml', :to => 'sitemaps#index', :defaults => {:format => 'xml'}
  get 'discourse/sso', to: 'discourse_sso#sso'

  resources :ideas do
    patch :repost, on: :member
    resources :payments, only: :create
    resources :flags, only: :create
    resources :implementations, only: [:index, :create, :new, :show]
    resources :comments, only: :create
    resources :backer_votes, only: [:new, :create]
  end

  resources :comments, only: [] do
    resources :flags, only: :create
  end

  resources :votes, only: [] do
    get :start, on: :collection
    post :finish, on: :collection
  end

  resources :users, only: [] do
    resources :ideas, only: [:index]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get :terms, to: 'main#terms'
  get :search, to: 'main#search'
  get :about, to: 'main#about'
  get :contest, to: 'main#contest'
  get :privacy_policy, to: 'main#privacy_policy'
  root to: 'main#index'
end

app/models/payment.rb
require 'paypal_sdk'

class Payment < ActiveRecord::Base
  belongs_to :sender, polymorphic: true
  belongs_to :recipient, polymorphic: true

  validates :amount, numericality: { greater_than_or_equal_to: 0.01 }, unless: :process_by_paypal?
  validates :amount, numericality: { greater_than_or_equal_to: 1 }, if: :process_by_paypal?

  delegate :url_helpers, to: 'Rails.application.routes'

  before_create :create_paypal_payment, if: :process_by_paypal?
  before_create :process_payment, unless: :process_by_paypal?

  scope :successful, -> { where("paypal_status = 'approved' OR paypal_id IS NULL") }

  def paypal_payment
    @payment ||= PaypalSdk::Payment.find(paypal_id)
  end

  def process_paypal_payment(opts)
    if (result = paypal_payment.execute(opts))
      Payment.transaction do
        recipient.lock!
        recipient.balance += amount
        recipient.save!
        self.paypal_status = paypal_payment.state
        self.transaction_fee = pp_transaction_fee
        self.paypal_payer_id = pp_payer_id
        save
        recipient.increment_backers_count!(sender) if recipient.respond_to? :increment_backers_count!
      end
    end
    result
  end

  def process_by_paypal?
    sender_type == 'User' && recipient_type == 'Idea' && sender.balance < amount
  end

  def paypal_payment?
    paypal_id.present? && paypal_status == 'approved'
  end

  private

  def process_payment
    Payment.transaction do
      sender.lock!
      recipient.lock!
      sender.balance -= amount
      sender.save!
      recipient.balance += amount
      recipient.increment_backers_count!(sender) if recipient.respond_to? :increment_backers_count!
      recipient.save!
    end
  end

  def create_paypal_payment
    @payment = PaypalSdk::Payment.new({
                               intent:        'sale',
                               payer:         { payment_method: 'paypal' },
                               redirect_urls: {
                                   return_url: url_helpers.callback_payments_url(host: ENV['APPLICATION_URL']),
                                   cancel_url: url_helpers.idea_url(recipient, host: ENV['APPLICATION_URL'], status: :canceled)
                               },
                               transactions:  [
                                                  {
                                                      item_list:   {
                                                          items: [
                                                                     {
                                                                         name:     "Funding of #{recipient.title}",
                                                                         sku:      "#{recipient_type.downcase}_#{recipient_id}",
                                                                         price:    paypal_amount,
                                                                         currency: 'USD',
                                                                         quantity: 1
                                                                     }
                                                                 ]
                                                      },
                                                      amount:      {
                                                          total:    paypal_amount,
                                                          currency: 'USD'
                                                      },
                                                      description: 'IdeaDash idea funding.'
                                                  }
                                              ]
                           }
    )
    if @payment.create
      self.paypal_id     = @payment.id
      self.paypal_status = @payment.state
    else
      errors.add(:base, @payment.error[:details].map { |issue| issue[:issue] })
      return false
    end
  end

  def paypal_amount
    sprintf('%.2f', amount)
  end

  def pp_transaction_fee
    tr = paypal_payment.transactions.first
    return 0 if tr.nil?
    related = tr.related_resources.first
    return 0 if related.nil?
    related.sale.transaction_fee.value.to_f
  end

  def pp_payer_id
    paypal_payment.payer.payer_info.payer_id
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  load_resource :idea
  authorize_resource :payment

  def index
    @incoming_payments = current_user.incoming_payments.successful.includes(:sender).order(created_at: :desc).limit(5)
    @outgoing_payments = current_user.outgoing_payments.successful.includes(:recipient).order(created_at: :desc).limit(5)
  end

  def incoming
    @payments = current_user.incoming_payments.successful.includes(:sender).paginate(:page => params[:page])
  end

  def outgoing
    @payments = current_user.outgoing_payments.successful.includes(:recipient).paginate(:page => params[:page])
  end

  def create
    @payment = current_user.outgoing_payments.build(payment_params)
    if @payment.save
      if @payment.process_by_paypal?
        @payment = @payment.paypal_payment
        @redirect_url = @payment.links.find{|v| v.method == "REDIRECT" }.href
        redirect_to @redirect_url
      else
        redirect_to @idea, success: 'Funding is successful! Thank you for taking part in it!'
      end
    else
      redirect_to @idea, danger: "Funding is not successful. #{ @payment.errors.full_messages.join('. ') }."
    end
  end

  def callback
    @payment = Payment.where(paypal_id: params[:paymentId]).first
    return redirect_to root_path, warning: 'Something went wrong' if @payment.nil? || params[:paymentId].nil?

    if @payment.process_paypal_payment(:payer_id => params[:PayerID])
      session[:fbq] = [ '"Purchase"', { value: @payment.amount.to_f, currency: 'USD' }.to_json ].join(', ')
      redirect_to @payment.recipient, success: 'Funding is successful! Thank you for taking part in it!'
    else
      redirect_to @payment.recipient, warning: 'Funding is not successful!'
    end
  end

  private
  def payment_params
    params.require(:payment).permit(:amount).merge(recipient: @idea)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
  def humanize_payment_kind kind
    case kind
      when 'funding' then 'Idea funding'
      when 'ideadash_fee' then 'IdeaDash fee'
      when 'author_reward' then 'Author reward'
      when 'implementation_funds' then 'Implementation funds'
    end
  end
end

app/views/payments/_incoming_payment.slim
= content_tag_for :tr, incoming_payment do
  td= link_to incoming_payment.sender.title, incoming_payment.sender
  td= humanize_payment_kind incoming_payment.kind
  td.amount
    = decimal_number incoming_payment.amount
    ' $

app/views/payments/_outgoing_payment.slim
= content_tag_for :tr, outgoing_payment do
  td= link_to outgoing_payment.recipient.title, outgoing_payment.recipient
  td.amount
    = decimal_number outgoing_payment.amount
    ' $

app/views/payments/incoming.slim
- provide :title, 'Incoming payments'
.col-xs-12.col-md-offset-1.col-md-10
  h3 Incoming Payments
  table.table#incoming_payments
    thead
      tr
        th From
        th Amount
    tbody
      = render collection: @payments, partial: 'incoming_payment'
  = will_paginate @payments, renderer: BootstrapPagination::Rails

app/views/payments/index.slim
- provide :title, 'Payments'
.col-xs-12.col-md-offset-1.col-md-10
  .row
    .col-xs-12.col-md-4
      h4 Your balance: #{ decimal_number current_user.balance }$
    .col-xs-12.col-md-4
      h4 You funded: #{ current_user.outgoing_payments.successful.count } ideas
    .col-xs-12.col-md-4
      h4 You received: #{ current_user.incoming_payments.successful.count } transfers
  - unless @incoming_payments.empty?
    h3
      ' Recent incoming payments
      span.small= link_to '(see all)', incoming_payments_path
    table.table#incoming_payments
      thead
        tr
          th From
          th Kind
          th Amount
      tbody
        = render collection: @incoming_payments, partial: 'incoming_payment'
  - unless @outgoing_payments.empty?
    h3
      ' Recent outgoing payments
      span.small= link_to '(see all)', outgoing_payments_path

    table.table#outgoing_payments
      thead
        tr
          th To
          th Amount
      tbody
        = render collection: @outgoing_payments, partial: 'outgoing_payment'

app/views/payments/outgoing.slim
- provide :title, 'Payments'
.col-xs-12.col-md-offset-1.col-md-10
  h3 Outgoing payments

  table.table#outgoing_payments
    thead
      tr
        th To
        th Amount
    tbody
      = render collection: @payments, partial: 'outgoing_payment'
  = will_paginate @payments, renderer: BootstrapPagination::Rails